### ISSUE TITLE
Move Dockerfiles to the top dir, or in a separate dir `docker`

### ISSUE THREAD

**Issue by drasko** [feclare/edgex-go#2]
No need  to make them workable, we just need a visual representation, so that we can see how we can organize different `Dockerfile`s and `docker-compose.yaml`s (i.e. make some conventions about different Dockerfile naming, etc..)

**Comment by feclare** [comment]
Just moved to ./dockerfiles

**Comment by drasko** [comment]
I would propose `docker` both for the simplicity and also for the fact that `docker-compose.yaml` files and other docker-related artifacts would probably live there also, not only `Dockerfile`s

**Comment by feclare** [comment]
Done
